# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantlin', models.IntegerField(verbose_name='Pantlin')),
                ('firman', models.IntegerField(verbose_name='Firman')),
                ('goodman', models.IntegerField(verbose_name='Goodman')),
                ('datesubmitted', models.DateTimeField(verbose_name='Date submitted')),
                ('submitby', models.CharField(max_length=50, verbose_name='Submitted by')),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
