# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('housepoints', '0003_auto_20170929_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepoints',
            name='datesubmitted',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 29, 9, 44, 50, 789522, tzinfo=utc), verbose_name='Date submitted'),
        ),
    ]
