# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('housepoints', '0004_housepoints_datesubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepoints',
            name='datesubmitted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date submitted'),
        ),
    ]
