# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housepoints', '0006_auto_20170929_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepoints',
            name='shortreason',
            field=models.CharField(default='', max_length=100, verbose_name='Reason'),
        ),
    ]
