# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 20:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housepoints', '0007_housepoints_shortreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepoints',
            name='shortreason',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Reason'),
        ),
    ]
