# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 07:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housepoints', '0010_auto_20170929_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(verbose_name='Start Date')),
                ('enddate', models.DateField(verbose_name='End Date')),
                ('displayyear', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Display Year')),
            ],
        ),
        migrations.AddField(
            model_name='housepoints',
            name='displayyear',
            field=models.ForeignKey(default=2016, on_delete=django.db.models.deletion.PROTECT, to='housepoints.AccademicYear'),
            preserve_default=False,
        ),
    ]
